title = "COVID-19 Tracing"
disableKinds = ["taxonomy", "taxonomyTerm"]
baseURL = "https://covid19tracing.org"
theme = "covid19"
enableRobotsTXT = true
defaultContentLanguage = "en"

[markup.goldmark.renderer]
  unsafe= true

[permalinks]
  posts = "/:slug/"

[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en"
    weight = 1
      [[languages.en.menu.main]]
      identifier = "about"
      name = "About"
      url = "/about/"
      weight = 1

    [[languages.en.menu.main]]
      identifier = "map"
      name = "Map"
      url = "/map/"
      weight = 2

    [[languages.en.menu.main]]
      name = "Share your data"
      identifier = "newcase"
      url = "/newcase/"
      weight = 3

  [languages.pt]
    languageName = "Português"
    languageCode = "pt"
    weight = 2
    
    [[languages.pt.menu.main]]
      identifier = "about"
      name = "Sobre"
      url = "/pt/about/"
      weight = 1

    [[languages.pt.menu.main]]
      identifier = "map"
      name = "Mapa"
      url = "/pt/map/"
      weight = 2

    [[languages.pt.menu.main]]
      name = "Adicionar um novo caso"
      identifier = "newcase"
      url = "/pt/newcase/"
      weight = 3